- project:
    templates:
      - tempest-plugin-jobs
      - check-requirements
    check:
      jobs: &cloudkitty_tempest_jobs
        - cloudkitty-tempest-full-v2-storage-influxdb:
            voting: true
        - cloudkitty-tempest-full-v1-storage-sqlalchemy:
            voting: true
        - cloudkitty-tempest-full-v2-storage-elasticsearch:
            voting: true
        - cloudkitty-tempest-full-v2-storage-influxdb-wallaby
        - cloudkitty-tempest-full-v2-storage-influxdb-victoria
        - cloudkitty-tempest-full-v2-storage-influxdb-ussuri
        - cloudkitty-tempest-full-v2-storage-influxdb-train
    gate:
      queue: cloudkitty
      jobs: *cloudkitty_tempest_jobs

- job:
    name: cloudkitty-tempest-full-v2-storage-influxdb-wallaby
    parent: cloudkitty-tempest-full-v2-storage-influxdb
    override-checkout: stable/wallaby

- job:
    name: cloudkitty-tempest-full-v2-storage-influxdb-victoria
    parent: cloudkitty-tempest-full-v2-storage-influxdb
    override-checkout: stable/victoria

- job:
    name: cloudkitty-tempest-full-v2-storage-influxdb-ussuri
    parent: cloudkitty-tempest-full-v2-storage-influxdb
    override-checkout: stable/ussuri

- job:
    name: cloudkitty-tempest-full-v2-storage-influxdb-train
    parent: cloudkitty-tempest-full-v2-storage-influxdb
    override-checkout: stable/train
    vars:
      devstack_localrc:
        USE_PYTHON3: True
